FROM apache/kafka:3.7.1

ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller

# Bind to all IPv4 interfaces explicitly
ENV KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092

ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_LOG_DIRS=/var/lib/kafka/data

# Disable IPv6 to prevent ::1 connections
ENV KAFKA_OPTS="-Djava.net.preferIPv4Stack=true"

EXPOSE 9092