FROM apache/kafka:3.7.1

ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
ENV KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_LOG_DIRS=/var/lib/kafka/data
ENV KAFKA_OPTS="-Djava.net.preferIPv4Stack=true"

COPY --chmod=755 entrypoint.sh /entrypoint.sh

EXPOSE 9092
ENTRYPOINT ["/entrypoint.sh"]
