FROM bitnami/kafka:3.6.1

ENV KAFKA_ENABLE_KRAFT=yes
ENV KAFKA_CFG_PROCESS_ROLES=broker,controller
ENV KAFKA_CFG_NODE_ID=1
ENV KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
ENV KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
ENV KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
ENV ALLOW_PLAINTEXT_LISTENER=yes

EXPOSE 9092